version: '3.8'

services:
  # Laravel backend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - laravel_network
    depends_on:
      - db

  # Vue frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    networks:
      - laravel_network

  # MySQL database
  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network
    ports:
      - "3306:3306"

volumes:
  dbdata:

networks:
  laravel_network:
    driver: bridge
